var planetList =
[
  {
      "name": "moon",
      "diameter": 3475,
      "day": 708.7,
      "semi-major": 0.384,
      "perihelion": 0.363,
      "aphelion": 0.406,
      "orbital_period": 27.3,
      "orbital_velocity": 1,
      "orbital_inclination": 5.1,
      "orbital_eccentricity": 0.055,
      "texture":"texture/2k_moon.jpg",
      "axial_tilt": 1.54,
  },
    {
        "name": "mercury",
        "diameter": 4879,
        "day": 4222.6,
        "semi-major": 57.9,
        "perihelion": 46,
        "aphelion": 69.8,
        "orbital_period": 88,
        "orbital_velocity": 47.4,
        "orbital_inclination": 7,
        "orbital_eccentricity": 0.205,
        "texture":"texture/2k_mercury.jpg",
        "axial_tilt": 0.01,
    },
    {
        "name": "venus",
        "diameter": 12104,
        "day": -2802,
        "semi-major": 108.2,
        "perihelion": 107.5,
        "aphelion": 108.9,
        "orbital_period": 224.7,
        "orbital_velocity": 35,
        "orbital_inclination": 3.4,
        "orbital_eccentricity": 0.007,
        "texture":"texture/2k_venus_surface.jpg",
        "axial_tilt": 2.64,
    },
    {
        "name": "earth",
        "diameter": 12756,
        "day": 24,
        "semi-major": 149.6,
        "perihelion": 147.1,
        "aphelion": 152.1,
        "orbital_period": 365.2,
        "orbital_velocity": 29.8,
        "orbital_inclination": 0,
        "orbital_eccentricity": 0.017,
        "texture":"texture/2k_earth_daymap.jpg",
        "axial_tilt": 23.44,
    },
    {
        "name": "mars",
        "diameter": 6792,
        "day": 24.7,
        "semi-major": 227.9,
        "perihelion": 206.6,
        "aphelion": 249.2,
        "orbital_period": 687,
        "orbital_velocity": 24.1,
        "orbital_inclination": 1.9,
        "orbital_eccentricity": 0.094,
        "texture":"texture/2k_mars.jpg",
        "axial_tilt": 25.19,
    },
    {
        "name": "jupiter",
        "diameter": 142984,
        "day": 9.9,
        "semi-major": 778.6,
        "perihelion": 740.5,
        "aphelion": 816.6,
        "orbital_period": 4331,
        "orbital_velocity": 13.1,
        "orbital_inclination": 1.3,
        "orbital_eccentricity": 0.049,
        "texture":"texture/2k_jupiter.jpg",
        "axial_tilt": 3.12,
    },
    {
        "name": "saturn",
        "diameter": 120536,
        "day": 10.7,
        "semi-major": 1433.5,
        "perihelion": 1352.6,
        "aphelion": 1514.5,
        "orbital_period": 10747,
        "orbital_velocity": 9.7,
        "orbital_inclination": 2.5,
        "orbital_eccentricity": 0.057,
        "texture":"texture/2k_saturn.jpg",
        "axial_tilt": 26.73,
    },
    {
        "name": "uranus",
        "diameter": 51118,
        "day": -17.2,
        "semi-major": 2872.5,
        "perihelion": 2741.3,
        "aphelion": 3003.6,
        "orbital_period": 30589,
        "orbital_velocity": 6.8,
        "orbital_inclination": 0.8,
        "orbital_eccentricity": 0.046,
        "texture":"texture/2k_uranus.jpg",
        "axial_tilt": 82.23,
    },
    {
        "name": "neptune",
        "diameter": 49528,
        "day": 16.1,
        "semi-major": 4495.1,
        "perihelion": 4444.5,
        "aphelion": 4545.7,
        "orbital_period": 59800,
        "orbital_velocity": 5.4,
        "orbital_inclination": 1.8,
        "orbital_eccentricity": 0.011,
        "texture":"texture/2k_neptune.jpg",
        "axial_tilt": 28.33,
    },
    {
        "name": "pluto",
        "diameter": 2370,
        "day": 153.3,
        "semi-major": 5906.4,
        "perihelion": 4436.8,
        "aphelion": 7375.9,
        "orbital_period": 90560,
        "orbital_velocity": 4.7,
        "orbital_inclination": 17.2,
        "orbital_eccentricity": 0.244,
        "texture":"texture/pluto.jpg",
        "axial_tilt": 60.41,
    }
]

//Calculate semi-minor using b^2=a^2(1-e^2)
planetList.forEach((planet, i) => {
  planet['semi-minor'] = ((planet['semi-major']**2)*(1-planet['orbital_eccentricity']**2))**(1/2)
});

// console.log(planetList)
